package org.create.bankingApplication.user_service.model.entity;

import java.time.LocalDate;

import org.create.bankingApplication.user_service.model.Status;
import org.hibernate.annotations.CurrentTimestamp;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


/*
 	This class is for User's data which is used for authentication purpose
 */

@Entity
@Data                 //generates getters and setters
@NoArgsConstructor    //generates constructor with no fields
@AllArgsConstructor   //generates constructor with all fields
@Builder   			  //build object
public class User {
	
	@Id                       //primary key for db
	@GeneratedValue(strategy = GenerationType.IDENTITY)         //Identity=> autogenerated by db
	private Long userId;
	
	private String emailId;
	
	private String authenticationId;
	
	private String contactNo;
	
	private String identificationNo;
	
	@CurrentTimestamp
	private LocalDate createdOnDate;
	
	/*
	 Stored all constant values from Status enum as string 
	 */
	
	@Enumerated(EnumType.STRING)
	private Status status;
	
	/* One-to-one relationship between User <-> UserProfile
	 Cascade=ALL {operations will affect both tables}, Foreign Key = user_profile_id */
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "user_profile_id" , referencedColumnName = "userProfileId")
	private UserProfile userProfile;
	
}
